regionx             = "us-east-1"
cidr_block          = "10.1.0.0/16"
subnets             = ["10.1.1.0/24" , "10.1.2.0/24"]
availabilty_zones   = ["us-east-1a" , "us-east-1b"]
ami_id              = "ami-08982f1c5bf93d976"
instance_type       = "t3.medium"
allocated_storage   = "20"
storage_type        = "gp2"
engine              = "mysql"
engine_version      = "5.7"
instance_class      = "db.t3.medium"
db_identifier       = "dev-db"
username            = "devuser"
password            = "devpassword"
parameter_group_name= "default.mysql5.7"
bucket_name         = "pract-dev-website"
key_name            = "Practkey"
allowed_ports       = [22, 3000, 9090]
allowed_cidr_blocks = ["0.0.0.0/0"]

